### PR TITLE
Added instructions to set up Tobii passthough with Windows VM

### PR DESCRIPTION
**Pull request by jjcantillon**
For penguins that are stubborn about using their overpriced hardware I have written a guide that can be used to set up a VM that can be used to connect to the Tobii Eye Tracker 5 and then pass the tracking data using Opentrack back to the linux host for use with Star Citizen.

### CODE REVIEW

**Comment by the-sane** [comment]
This is still head tracking only, right, no eye tracking? We should probably add a note at the top to clarify that.

**Comment by jjcantillon** [comment]
> This is still head tracking only, right, no eye tracking? We should probably add a note at the top to clarify that.

This does not enable targeting based on eye tracking but you can use eye tracking for camera movements. I will add something to clarify this.

**Comment by jjcantillon** [comment]
@the-sane Clarification on eye tracking limitation added.

**Comment by the-sane** [comment]
Thanks for putting this together

**Comment by the-sane** [comment]
Oh, just noticed a final thing before merging. Rather than put images in a separate folder like that, if you use the web interface to drag them into the code it'll upload and link them. I don't know if there are any downsides to that, but it's what we've been doing so far and I'd prefer to continue doing it that way for the sake of consistency. If we switch to using an images subdirectory, I'd want to do it for all the images to maintain consistency. That may be a later project if there's some benefit to doing it that way. For now, would you mind switching that?

**Comment by jjcantillon** [comment]
> Oh, just noticed a final thing before merging. Rather than put images in a separate folder like that, if you use the web interface to drag them into the code it'll upload and link them. I don't know if there are any downsides to that, but it's what we've been doing so far and I'd prefer to continue doing it that way for the sake of consistency. If we switch to using an images subdirectory, I'd want to do it for all the images to maintain consistency. That may be a later project if there's some benefit to doing it that way. For now, would you mind switching that?

I don't normally use the GitHub web interface but I have uploaded them this way to match the rest of the images.

I do think there are some advantages if you want to switch the images:

- Images become part of source control and may be easier to spot a change in a diff when looking at the file list
- Images are not tied to a user account but are part of the repository
- Updating and adding images is possible without using the GitHub web interface 
- Repository is not reliant on GitHub if it was to go down or you wanted to change hosting provider

If you decide later you would like to swap them I could help out on another branch / PR.

**Comment by the-sane** [comment]
You make some good points. It probably is a good idea to switch over then. If you're willing to help that'd be awesome, though it's not an immediate need.

I'll merge this as is for now and let's continue the images discussion over in Discord. We'll need to come up with a file naming convention that allows something looking at the image files to know where in the wiki that image is used.

**Pull request merged**
