### PR TITLE
Add sticks and throttles option for saitek rhino pro x55/56 and input-remapper

### PR DESCRIPTION
**Pull request by arkhoss**
This MR does the following:

- Add option for configuration of Saitek Rhino pro X55/X56 
- Add recommendation in mappings section to other devices

Dependency: 

This MR depends of the approval for:

https://github.com/starcitizen-lug/mappings/pull/1

### CODE REVIEW

**Comment by the-sane** [comment]
Thanks for the PR!

Have we vetted the input-remapper software being recommended here? I took a cursory glance at it and it’s a non-trivial piece of software that even appears to install a daemon on the machine. 

I want to make sure we don’t recommend anything on our wiki that hasn’t been fully vetted by us since we have a lot of brand new penguins who rely on us to provide safe recommendations while they learn the ropes.

**Comment by arkhoss** [comment]
No, It haven been vetted, and true, is not a trivial piece of software, should I do something to help in the vetting process? or LUG development team will discuss it? I'm new in LUG so not fully aware of your process. :smiley:

**Comment by the-sane** [comment]
That’s okay and we always appreciate contributions to our wiki!

I will likely ask some of the others in our community if they’ve heard of or are involved in the development of this software and take it from there. Unless we have some folks who are super familiar with it, I’m not sure I’m comfortable merging this into the wiki. We may be able to find another way to make the information available to those who wish to try it though. I’ll give that some thought and look into it when I can, just give me a bit of time with it.

**Comment by arkhoss** [comment]
Thank you for the consideration and care, no rush from my side, always better keep security in mind.  cya in the verse!

**Comment by the-sane** [comment]
@arkhoss A question for you: How does this stick & throttle behave without input-remapper? Is it required for basic functionality or are you using it to completely customize some things to your liking?

**Comment by arkhoss** [comment]
Hi @the-sane ,

I'm using it to customize things to my liking, specially cuz I haven't found any way to do some of it in the StarCizen Joystick profiles.

**Comment by the-sane** [comment]
Whoops, I forgot about this one. I'm going to merge it and then make some tweaks to make it clear that it's a third party tool

**Pull request merged**
