### PR TITLE
Update Tips-and-Tricks: Add NixOS configuration options

### PR DESCRIPTION
**Pull request by LovingMelody**

### CODE REVIEW

**Comment by the-sane** [comment]
Thanks a lot for putting this together! I wrote some minor change requests in a review. The EAC manual configuration section should be linkable after you rebase

**Review by the-sane — CHANGES_REQUESTED** [review]
Apparently I forgot to submit the review so you could see my comments. Oopsies!

**Comment by LovingMelody** [comment]
Sorry for the delay, it should be good now.

**Comment by the-sane** [comment]
Thank you!

**Pull request merged**
