### PR TITLE
Add section on evdev deadzone removal

### PR DESCRIPTION
**Pull request by profdecoy**

### CODE REVIEW

**Comment by the-sane** [comment]
Nicely done! That's a lot of detail.

Question: Where does `/usr/bin/evdev-joystick` come from?

**Comment by profdecoy** [comment]
On Ubuntu it comes from the `joystick` package.

**Comment by the-sane** [comment]
We'll need to add, at minimum, a generic instruction to install this package, but it would be best if we can also put together a list of how people can install it for various distros before we publish this on the wiki. I'm sure folks on the discord can help with a list.

For Arch, it looks like it's provided by the `linuxconsole` package.

Looking at the arch wiki page on this, here's the section for the evdev api. Does the Arch version of evdev-joystick use the same commands and format as yours?
https://wiki.archlinux.org/title/Gamepad#evdev_API_deadzones

Perusing that article, there are three other types of deadzones mentioned. Wine deadzones, Xorg deadzones, and Joystick API deadzones. Do you know what these are? Do they need to be changed also for some people or will the evdev api do it for everyone? The three start in order here:
https://wiki.archlinux.org/title/Gamepad#Wine_deadzones

**Comment by profdecoy** [comment]
From My testing, only the Evdev deadzones mattered for wine.  The older joystick calibration via jstest using the `/dev/input/jsX` devices using had no effect, and the jstest-gtk page even indicates that the jsX device is obsolete, and everything new should be using the `/dev/input/eventX` devices:

https://jstest-gtk.gitlab.io/

As for the Arch wiki page for the evdev deadzones, yes it matches what I have available with evdev.  So for debian based distros, will want to install the `joystick` package, and for Arch `linuxconsole`.  Do we know what it is for Fedora?

**Comment by profdecoy** [comment]
Looks like it's `linuxconsoletools` for Fedora, will add those in.

**Comment by the-sane** [comment]
:+1:  Thanks for putting this together!

**Comment by profdecoy** [comment]
You're welcome.

**Pull request merged**
