### PR TITLE
Added guide to set up Opentrack with Neuralnet.

### PR DESCRIPTION
**Pull request by DavSladk**
I was able to set up Opentrack with Neuralnet input to use my webcam for head tracking. Since I wasn't able to find any guide on this online, I figured that I could share a guide with other LUG members. Please review and provide feedback.

### CODE REVIEW

**Comment by the-sane** [comment]
Hey! Thanks for the guide.
Question: [This](https://github.com/opentrack/opentrack/wiki/AI-Face-Tracking) says Neuralnet is
> included in Opentrack, no additional installation necessary

So what's up with that onnx runtime from microsoft? Is that necessary to make Neuralnet work?

I'm concerned about the privacy policy of that AI tool. In their readme, they say:
> Windows distributions of this project may collect usage data and send it to Microsoft to help improve our products and services.

That could change at any point to become "all distributions" rather than just windows.

**Comment by DavSladk** [comment]
1) This is indeed true for the Windows build that Opentrack provides since it includes ONNX runtime `.dll`. Unfortunately, this is not true when building from the source, and the Linux `.so` must be manually provided.

2) Unfortunately I can not make any guarantees regarding Microsoft. Even [this](https://github.com/microsoft/onnxruntime/blob/main/docs/Privacy.md) from the ONNX repo plays into your concern. However, it also mentions that private builds have no telemetry. If required, I can expand the guide to include how to build the ONNX runtime.

**Comment by the-sane** [comment]
I see. Alright, so here are my thoughts on this so far: I'd like to include this in the wiki directly on the tips and tricks page. There's a lot of detail here, which is great, but I have a couple concerns about including all of it. Firstly, if we include this level of detail for all of these types of things, our wiki will become monstrous and unmaintainable. Secondly, our wiki really isn't meant to be a step by step guide for users who are new to linux and would need this kind of guide. I also feel like those users would benefit far more from talking to folks on our discord where we can explain why things are they way they are and provide added context and learning opportunities that a guide can't provide no matter how much detail is in it.

So, how do you feel about creating a vastly simplified version of this? Specifically, I'm thinking:
- A new subheading under the existing opentrack section for "building with neuralnet for face tracking" or something similar.
- A line that briefly explains what building with onnx will do for the user or why they might want to do this to add context to the section
- Simplify the build instructions. Let's assume users are smart enough to follow opentrack's instructions and, rather then re-create them, let's just link to that.
- Skip the rest of the stuff about creating folders, a shortcut, changing the path, etc. If you really want to include something about making a shortcut, let's link to a resource that provides more information like the arch wiki's [entry](https://wiki.archlinux.org/title/Desktop_entries#File_example) instead. I'd like to teach new users how to find this information rather than just provide it for them.

Thoughts?

**Comment by DavSladk** [comment]
You raise valid points. I wanted to make it fit more in the current LUG wiki format originally, but at some point, I got carried away.

I will look into it and reduce the guide.

**Comment by DavSladk** [comment]
The guide is reduced in size and integrated under the Opentrack section. Feel free to review.

**Comment by the-sane** [comment]
Looks great, thanks! We can always add a bit of extra detail if other users are running into snags.

**Pull request merged**
